swagger: "2.0"
info:
  title: Pokémon API
  description: An API to retrieve a list of Pokemon and fetch detailed information on each Pokemon using the PokeAPI.
  version: "1.0.0"
host: pokemon-app:8000
basePath: /api/v1/pokemon
schemes:
  - http

paths:
  /pokeapi.co/api/v2/pokemon:
    get:
      summary: Get a list of all available Pokemon
      description: Fetches a paginated list of Pokémon with basic details.
      tags:
        - Pokemon
      parameters:
        - name: offset
          in: query
          description: Page number for pagination.
          required: false
          type: integer
          default: 20
        - name: limit
          in: query
          description: Number of Pokemon per page.
          required: false
          type: integer
          default: 20
      responses:
        "200":
          description: A paginated list of Pokémon.
          schema:
            $ref: '#/definitions/PokemonResponseList'
        "500":
          description: Internal server error.
          schema:
            $ref: '#/definitions/ErrorResponse'

  /pokemon/{name}:
    get:
      summary: Get details for a specific Pokemon
      description: Fetches detailed information for a specific Pokemon by its name.
      tags:
        - Pokemon
      parameters:
        - name: name
          in: path
          description: Name of the Pokemon to retrieve.
          required: true
          type: string
      responses:
        "200":
          description: Pokemon details retrieved successfully.
          schema:
            $ref: '#/definitions/PokemonDetail'
        "404":
          description: Pokémon not found.
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error.
          schema:
            $ref: '#/definitions/ErrorResponse'

definitions:
  PokemonResponseList:
    type: object
    properties:
      count:
        type: integer
        description: Total count of Pokemon available.
        example: 1118
      next:
        type: string
        description: URL for the next page of results.
        example: "https://pokeapi.co/api/v2/pokemon?offset=1120&limit=100"
      previous:
        type: string
        description: URL for the previous page of results.
        example: null
      results:
        type: array
        items:
          $ref: '#/definitions/PokemonBasicInfo'

  PokemonBasicInfo:
    type: object
    properties:
      name:
        type: string
        description: Name of the Pokémon.
        example: pikachu
      url:
        type: string
        description: URL to fetch details for the Pokémon.
        example: "https://pokeapi.co/api/v2/pokemon/pikachu"

  PokemonDetail:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier for the Pokémon.
        example: 25
      name:
        type: string
        description: Name of the Pokémon.
        example: pikachu
      height:
        type: integer
        description: Height of the Pokémon in decimeters.
        example: 4
      weight:
        type: integer
        description: Weight of the Pokémon in hectograms.
        example: 60
      types:
        type: array
        description: List of types for the Pokémon.
        items:
          $ref: '#/definitions/PokemonType'
      abilities:
        type: array
        description: List of abilities for the Pokémon.
        items:
          $ref: '#/definitions/PokemonAbility'
      sprites:
        type: object
        description: Image of search PoKemon
        example: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10277.png"

  PokemonType:
    type: object
    properties:
      slot:
        type: integer
        description: Slot number for the type.
        example: 1
      type:
        type: object
        properties:
          name:
            type: string
            description: Name of the type.
            example: electric
          url:
            type: string
            description: URL to type details.
            example: "https://pokeapi.co/api/v2/type/13/"

  PokemonAbility:
    type: object
    properties:
      ability:
        type: object
        properties:
          name:
            type: string
            description: Name of the ability.
            example: static
          url:
            type: string
            description: URL to ability details.
            example: "https://pokeapi.co/api/v2/ability/31/"
      is_hidden:
        type: boolean
        description: Indicates if the ability is hidden.
        example: false
      slot:
        type: integer
        description: Slot number for the ability.
        example: 1

  ErrorResponse:
    type: object
    properties:
      message:
        type: string
        description: Error message.
        example: "An error occurred while processing your request."
